env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[0f5b6ed5adddef0934e9bd4dd7cbdc3f3f0f24ac19743e4e336e0b92b07d0903b80f429720f3f6ca341af5e8f513f361]"

task:
  container:
    image: geopd/builder:update
    cpu: 9
    memory: 24G

  name: rom
  timeout_in: 120m
  download_ccache_background_script:
      - cd /tmp && mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - rclone copy drive:/UB /tmp -P && tar xf ccache.tar.gz
  build_script:
      - bash build.sh
  upload_ccache_script:
      - cd /tmp && tar --use-compress-program="pigz -k -1 " -cf ccache.tar.gz ccache
      - rclone copy ccache.tar.gz drive:/UB -P
