env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[73af55bad56866f0bb8998195fbfd7c8331f5c51458881b941beacbc7a2335b62335d8d25f8fda07542b6bd5bac7e751]"
    TOKEN: "ENCRYPTED[e62157dcbf118fdc8fb43a474b87a4c49e56e5412cd3a7a54447cb11904d42ddf7993e7c8aba62fdebd46a84668cbb66]"
    CHATID: "ENCRYPTED[cd6ef016b2ddf288f87fd6bc3b288c73f0f409a2f3726ea60fcafb6f4b289b23bdd23deb2537a5fad2781647c3f52005]"
    BOTTOKEN: "1445651245:AAGK9FrmOt3iKu5VkzYO8Ve7kjYXeYtzSc8"

task:
  container:
    image: geopd/builder:update
    cpu: 16
    memory: 24G

  name: rom
  timeout_in: 120m
  download_ccache_background_script:
      - cd /tmp && mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - rclone copy brrbrr:/ccache/ccache.tar.gz /tmp -P && tar xf ccache.tar.gz
  build_script:
      - bash build.sh
  upload_ccache_script:
      - cd /tmp && tar --use-compress-program="pigz -k -1 " -cf ccache.tar.gz ccache
      - rclone copy ccache.tar.gz brrbrr:/ccache -P
