env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[73af55bad56866f0bb8998195fbfd7c8331f5c51458881b941beacbc7a2335b62335d8d25f8fda07542b6bd5bac7e751]"

task:
  container:
    image: geopd/builder:update
    cpu: 16
    memory: 24G

  name: rom
  timeout_in: 120m
  download_ccache_background_script:
      - cd /tmp && mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - rclone copy drive:/UB /tmp -P && tar xf ccache.tar.gz
  build_script:
      - bash build.sh
  upload_ccache_script:
      - cd /tmp && tar --use-compress-program="pigz -k -1 " -cf ccache.tar.gz ccache
      - rclone copy ccache.tar.gz drive:/UB -P
